create table if not exists public.perfiles (
  id bigint generated by default as identity primary key,
  auth_user_id uuid references auth.users(id) on delete cascade unique,
  nombre text not null,
  email text not null unique,
  rol text not null check (rol in ('docente', 'directivo', 'padre', 'estudiante')),
  iniciales text not null,
  creado_en timestamptz default now()
);

create or replace function public.crear_perfil_usuario()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.perfiles (auth_user_id, nombre, email, rol, iniciales)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'nombre', split_part(new.email, '@', 1)),
    new.email,
    coalesce(new.raw_user_meta_data->>'rol', 'estudiante'),
    upper(left(coalesce(new.raw_user_meta_data->>'nombre', new.email), 1))
  )
  on conflict (auth_user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists crear_perfil_usuario on auth.users;
create trigger crear_perfil_usuario
after insert on auth.users
for each row execute function public.crear_perfil_usuario();

create table if not exists public.estudiantes (
  id bigint generated by default as identity primary key,
  nombre text not null,
  curso text not null check (curso in ('9A', '9B', '9C', '10A')),
  email text not null unique,
  acudiente text not null,
  acudiente_email text not null,
  presente boolean not null default true,
  justificado boolean not null default false,
  creado_en timestamptz default now()
);

create table if not exists public.notas (
  estudiante_id bigint references public.estudiantes(id) on delete cascade,
  materia text not null check (materia in ('Matematicas', 'Espanol', 'Ciencias', 'Historia', 'Ingles')),
  periodo text not null check (periodo in ('1', '2', '3', '4')),
  nota1 numeric(3,1) not null default 0,
  nota2 numeric(3,1) not null default 0,
  nota3 numeric(3,1) not null default 0,
  ultima_modificacion bigint not null default 0,
  primary key (estudiante_id, materia, periodo)
);

create table if not exists public.comunicados (
  id bigint generated by default as identity primary key,
  titulo text not null,
  mensaje text not null,
  destinatario text not null,
  fecha date not null,
  tipo text not null check (tipo in ('info', 'alerta', 'urgente')),
  autor text not null
);

alter table public.perfiles enable row level security;
alter table public.estudiantes enable row level security;
alter table public.notas enable row level security;
alter table public.comunicados enable row level security;

create policy "perfiles lectura autenticada"
on public.perfiles for select
to authenticated
using (true);

create policy "perfiles insercion propia"
on public.perfiles for insert
to authenticated
with check (auth.uid() = auth_user_id);

create policy "perfiles actualizacion propia"
on public.perfiles for update
to authenticated
using (auth.uid() = auth_user_id)
with check (auth.uid() = auth_user_id);

create policy "academico lectura autenticada"
on public.estudiantes for select
to authenticated
using (true);

create policy "academico escritura autenticada"
on public.estudiantes for all
to authenticated
using (true)
with check (true);

create policy "notas lectura autenticada"
on public.notas for select
to authenticated
using (true);

create policy "notas escritura autenticada"
on public.notas for all
to authenticated
using (true)
with check (true);

create policy "comunicados lectura autenticada"
on public.comunicados for select
to authenticated
using (true);

create policy "comunicados escritura autenticada"
on public.comunicados for all
to authenticated
using (true)
with check (true);

insert into public.estudiantes (id, nombre, curso, email, acudiente, acudiente_email, presente, justificado) values
(1, 'Valentina Ospina', '9A', 'v.ospina@sge.com', 'Maria Ospina', 'padre@sge.com', true, false),
(2, 'Sebastian Mora', '9A', 's.mora@sge.com', 'Carlos Mora', 'c.mora@sge.com', false, false),
(3, 'Luisa Fernandez', '9B', 'l.fernandez@sge.com', 'Pedro Fernandez', 'p.fernandez@sge.com', true, false),
(4, 'Diego Salcedo', '9B', 'd.salcedo@sge.com', 'Ana Salcedo', 'a.salcedo@sge.com', true, false),
(5, 'Mariana Rios', '9A', 'estudiante@sge.com', 'Jorge Rios', 'j.rios@sge.com', false, true),
(6, 'Andres Gomez', '9C', 'a.gomez@sge.com', 'Laura Gomez', 'l.gomez@sge.com', true, false),
(7, 'Camila Herrera', '9C', 'c.herrera@sge.com', 'Rosa Herrera', 'r.herrera@sge.com', true, false),
(8, 'Juan Pablo Torres', '10A', 'jp.torres@sge.com', 'Luis Torres', 'l.torres@sge.com', false, false)
on conflict (id) do nothing;

insert into public.notas (estudiante_id, materia, periodo, nota1, nota2, nota3, ultima_modificacion)
select e.id, materia, periodo, 3.5, 3.8, 3.6, 0
from public.estudiantes e
cross join (
  values
    ('Matematicas', '1'), ('Matematicas', '2'), ('Matematicas', '3'), ('Matematicas', '4'),
    ('Espanol', '1'), ('Espanol', '2'), ('Espanol', '3'), ('Espanol', '4'),
    ('Ciencias', '1'), ('Ciencias', '2'), ('Ciencias', '3'), ('Ciencias', '4'),
    ('Historia', '1'), ('Historia', '2'), ('Historia', '3'), ('Historia', '4'),
    ('Ingles', '1'), ('Ingles', '2'), ('Ingles', '3'), ('Ingles', '4')
) as mp(materia, periodo)
on conflict (estudiante_id, materia, periodo) do nothing;

insert into public.comunicados (id, titulo, mensaje, destinatario, fecha, tipo, autor) values
(1, 'Entrega de boletines', 'Los boletines del periodo actual ya estan disponibles para consulta.', 'Todos los padres', '2026-05-18', 'info', 'Coordinacion'),
(2, 'Alerta academica', 'Algunos estudiantes requieren plan de mejora esta semana.', 'Grado 9A', '2026-05-17', 'alerta', 'Docente'),
(3, 'Reunion general', 'Reunion virtual de acudientes el viernes a las 6:00 PM.', 'Todos los padres', '2026-05-16', 'urgente', 'Directivo')
on conflict (id) do nothing;
